name: Admin CI

# Only on main, admin folder
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/admin/**'


jobs:
  deploy-admin:
    name: Deploy Admin Panel to Cloudflare Worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm -F "*admin" build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          packageManager: pnpm
          workingDirectory: packages/admin
          command: pages deploy dist --project-name=suggestion-box-admin
