name: Worker CI

# Only on main, worker folder
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/worker/**'


jobs:
  deploy-worker:
    name: Deploy Worker to Cloudflare Worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: pnpm build
        run: pnpm build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          packageManager: pnpm
          workingDirectory: packages/worker
          command: deploy
